name: generate
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'

jobs:
  Generator:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git submodule update --recursive --remote

          if [ -f uBlacklist.txt ]; then rm -v uBlacklist.txt; fi
          cat vendor.list | xargs -i sh -c 'cat {} >> uBlacklist.txt ; echo  >> uBlacklist.txt'
          ./removeDuplicateLines.py && mv -v output.txt uBlacklist.txt
          if [[ $(git diff HEAD uBlacklist.txt) ]]; then
            git commit -m "Update uBlacklist.txt" -a
          fi
          git push
